name: dbt Quick Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  DBT_PROFILES_DIR: .
  DBT_DEV_PATH: data/dev.duckdb
  DBT_PROD_PATH: data/prod.duckdb
  DBT_DEV_THREADS: 1
  DBT_PROD_THREADS: 4
  DBT_TARGET: prod  # Use prod target for CI/CD

jobs:
  quick-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create profiles.yml for CI/CD
        run: cp profiles.yml.template profiles.yml

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-duckdb==1.9.4
      
      - name: Create data directory
        run: mkdir -p data

      - name: Verify dbt configuration
        run: |
          dbt --version
          dbt debug --profiles-dir .

      - name: Run dbt parse
        run: |
          echo "Validating dbt project structure..."
          dbt parse --profiles-dir .
          echo "dbt project validation passed!"

      - name: Run data quality tests
        run: |
          echo "Running data quality tests..."
          dbt test --profiles-dir .
          echo "All tests passed!"

      - name: Check model freshness (if applicable)
        run: |
          echo "Checking model performance..."
          dbt compile --profiles-dir .
          echo "Models compile successfully!"
